---
- name: Instalar y Configurar AWS CloudWatch Agent
  hosts: debian_web 
  become: yes
  vars:
    # Ansible tomará estos valores de las variables que le pasemos desde Jenkins
    # Si no se pasan, quedarán vacías por seguridad
    aws_access_key: "{{ aws_access_key_env | default('') }}"
    aws_secret_key: "{{ aws_secret_key_env | default('') }}"
    aws_region: "us-east-1"

  tasks:
    - name: Asegurar que el directorio de descargas existe
      file:
        path: "/data-docker/tmp-descargas"
        state: directory
        mode: '0755'

    - name: Descargar paquete del agente
      get_url:
        url: "https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
        dest: "/data-docker/tmp-descargas/amazon-cloudwatch-agent.deb"

    - name: Instalar el agente de CloudWatch
      apt:
        deb: "/data-docker/tmp-descargas/amazon-cloudwatch-agent.deb"
        state: present

    - name: Crear directorio para credenciales de AWS (Root)
      file:
        path: /root/.aws
        state: directory
        mode: '0700'

    - name: Configurar credenciales de AWS para el agente
      copy:
        dest: /root/.aws/credentials
        content: |
          [default]
          aws_access_key_id = {{ aws_access_key }}
          aws_secret_access_key = {{ aws_secret_key }}
          region = {{ aws_region }}
        mode: '0600'

    - name: Configurar common-config.toml
      copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml
        content: |
          [credentials]
            shared_credential_profile = "default"
            shared_credential_file = "/root/.aws/credentials"

    - name: Crear archivo de configuración JSON
      copy:
        dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
        content: |
          {
            "agent": {
              "metrics_collection_interval": 10,
              "run_as_user": "root"
            },
            "metrics": {
              "namespace": "GNS3/Web",
              "metrics_collected": {
                "cpu": {
                  "measurement": ["cpu_usage_active"],
                  "metrics_collection_interval": 10,
                  "totalcpu": true
                }
              }
            }
          }

    - name: Iniciar el agente con la configuración de On-Premise
      command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m onPremise -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json

    - name: Habilitar y reiniciar el servicio
      systemd:
        name: amazon-cloudwatch-agent
        enabled: yes
        state: restarted

    - name: Limpiar el instalador
      file:
        path: "/data-docker/tmp-descargas/amazon-cloudwatch-agent.deb"
        state: absent